Twitter/urls.py
from django.conf.urls import url, include
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('twitt.urls')),
]

twitt/urls.py
"""""""""""""""""""""""""""""""""""""""""
# @author  sonus
# @date 02 - Apr - 2016
# @copyright sonus
# GitHub http://github.com/sonus21
"""""""""""""""""""""""""""""""""""""""""

from django.conf.urls import url, include

from .views import SignUpView, FollowUserView, custom_logout, AccountProfileView,\
	PostTwitView, FollowListView, EditTwitView, HomeView, MyTwitsView

from django.contrib.auth.views import *

urlpatterns = [

	url(r'^$', HomeView.as_view(), name='home'),

	url(r'^accounts/profile/?$', AccountProfileView.as_view(), name='profile'),
	url(r'^accounts/login/?$', login, name='login'),
	url(r'^accounts/signup/?$', SignUpView.as_view(), name='signup'),
	url(r'^accounts/logout/?$', custom_logout, name='logout'),

	url('^accounts/twit/?$', MyTwitsView.as_view(), name='my_twits'),

	url('^post/twit/?$', PostTwitView.as_view(), name='post_twit'),
	url('^following/?$', FollowListView.as_view(), name='following_list'),
	url('^edit/twit/(?P<pk>[0-9]+)/?$', EditTwitView.as_view(), name='edit_twit'),

	url('^search/user/?$', FollowUserView.as_view(), name='follow_user'),
	url('^search/twit/', include('haystack.urls')),
]

twitt/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User

from django.db import models

# Create your models here.
from django.utils.timezone import now


class Follow(models.Model):
	"""
	Define Follow model which will hold list of follower and following
	and time when he/she started following
	"""
	follower = models.ForeignKey(User, related_name='follower', db_index=True)
	following = models.ForeignKey(User, related_name='following', db_index=True)
	date = models.DateTimeField(default=now)

	class Meta:
		unique_together = ('follower', 'following')


class Twit(models.Model):
	"""
	Twit model which holds twit data
	"""
	content = models.CharField(max_length=140)
	posted_on = models.DateTimeField(default=now)
	updated_on = models.DateTimeField(default=now, db_index=True)
	author = models.ForeignKey(User, db_index=True)

	def save(self, *args, **kwargs):

		# At inital set both as current time

		if self.posted_on is None:
			self.posted_on = now()
			self.updated_on = now()
		else:
			self.updated_on = now()

		super(Twit, self).save(*args, **kwargs)

templates/account_profile.html
{% extends 'base.html' %}
{% block content %}
    <div style="margin: 0 auto; max-width: 400px">
        <p>User Details</p>
        <ul>
            <li>First Name: {{ user.first_name }}</li>
            <li>Last Name: {{ user.last_name }}</li>
            <li>Username: {{ user.username }}</li>
        </ul>
    </div>

{% endblock %}

templates/base.html
{% load  staticfiles %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap-responsive.min.css" %}">
    <link rel="stylesheet" href="{%static "css/font-awesome.min.css" %}">
    <link rel="stylesheet" href="{%static "css/main.css" %}">
</head>

<body>
{% block header %}
    <!--Header-->
    <header class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a id="logo" class="pull-left" href="/">MiniTwitter</a>
                <form class="pull-left" style="margin-top: 10px;margin-bottom: 0;" action="/search/twit" method="get">
                    <input type="text" name="q" placeholder="Search ...">
                    <button type="submit" style="margin-top: -10px" class="btn btn-primary"><i class="icon
                    icon-search"></i></button>
                </form>
                <div class="nav-collapse collapse pull-right">
                    <ul class="nav">
                        <li><a href="/">Home</a></li>
                        {% if not request.user.is_authenticated %}
                            <li><a  href="{% url 'login' %}">Login</a></li>
                        {% else %}
                            <li><a  href="{% url 'follow_user' %}">Follow</a></li>
                            <li><a  href="{% url 'following_list' %}">Following</a></li>
                            <li><a  href="{% url 'my_twits' %}">My Twits</a></li>
                            <li><a  href="{% url 'logout' %}">Logout</a></li>
                        {% endif %}
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>
    </header>
    <!-- /header -->
{% endblock %}
<!--Slider-->
<section>
    {% block content%}
        I am middle body
    {% endblock %}
</section>

<!--/bottom-->
{% block footer %}
    <footer id="footer">
        <div class="container">
            <div class="row-fluid">
                <div class="span5 cp">
                    &copy; 2013 <a target="_blank" href="http://shapebootstrap.net/" title="Free Twitter Bootstrap WordPress Themes and HTML templates">ShapeBootstrap</a>. All Rights Reserved.
                </div>
                <!--/Copyright-->

                <div class="span6">
                    <ul class="social pull-right">
                        <li><a href="#"><i class="icon-facebook"></i></a></li>
                        <li><a href="#"><i class="icon-twitter"></i></a></li>
                        <li><a href="#"><i class="icon-pinterest"></i></a></li>
                        <li><a href="#"><i class="icon-linkedin"></i></a></li>
                        <li><a href="#"><i class="icon-google-plus"></i></a></li>
                        <li><a href="#"><i class="icon-youtube"></i></a></li>
                        <li><a href="#"><i class="icon-tumblr"></i></a></li>
                        <li><a href="#"><i class="icon-dribbble"></i></a></li>
                        <li><a href="#"><i class="icon-rss"></i></a></li>
                        <li><a href="#"><i class="icon-github-alt"></i></a></li>
                        <li><a href="#"><i class="icon-instagram"></i></a></li>
                    </ul>
                </div>

                <div class="span1">
                    <a id="gototop" class="gototop pull-right" href="#"><i class="icon-angle-up"></i></a>
                </div>
                <!--/Goto Top-->
            </div>
        </div>
    </footer>
{% endblock %}
</body>
</html>

templates/edit_twit.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block content %}
    <form method="post" id="twit-post" class="center" action="{% url 'edit_twit' form.instance.pk %}">
        <fieldset>
            {{ form|bootstrap }}
            <input type="submit" class="btn btn-success pull-right" value="Submit">
            {% csrf_token %}
        </fieldset>
    </form>
{% endblock %}

templates/follow.html
{% extends 'base.html' %}
{% block title %}Follow Someone{% endblock %}
{% block content %}

    <div class="row-fluid" style="padding: 20px">
        {% if user_list %}
            {% for user in  user_list %}
                <div class="span3">
                    <h4>{{ user.first_name }} {{  user.last_name }}</h4>
                    <ul class="arrow">
                        <li>First Name: {{ user.first_name }} </li>
                        <li>Last Name: {{  user.last_name }}</li>
                        <li>Username: {{ user.username }}</li>
                    </ul>
                    <form method="post">
                        <input type="hidden" name="pk" value="{{ user.pk }}">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-success small" value="+Follow">
                    </form>
                </div>
            {% endfor %}
        {% else %}
            <b>No more user to follow</b>
        {% endif %}
    </div>
{% endblock %}

templates/following.html
{% extends 'base.html' %}
{% block title %}Following List{%endblock%}
{% block content %}
    <div class="row-fluid" style="padding: 20px">
        {% if following_list %}
            {% for user in  following_list %}
                <div class="span3">
                    <h4>{{ user.first_name }} {{  user.last_name }}</h4>
                    <ul class="arrow">
                        <li>First Name: {{ user.first_name }} </li>
                        <li>Last Name: {{  user.last_name }}</li>
                        <li>Username: {{ user.username }}</li>
                    </ul>
                </div>
            {% endfor %}
        {% else %}
            <b>You are not following any one! Please follow someone</b>
        {% endif %}
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block title %}Welcome To Simplified Twitter{% endblock %}
{% block content %}
    <section id="tweets" class="container">
        <div class="row-fluid">
            <div class="span8">
                <div class="blog">

                    <form method="post" id="twit-post" class="center" action="/post/twit">
                        <fieldset>
                            {{ post_form|bootstrap }}
                            <input type="submit" class="btn btn-success pull-right" value="Submit">
                            {% csrf_token %}
                        </fieldset>
                    </form>
                    {% for twit in twits %}
                        <div class="blog-item well">
                            <p>{{ twit.2 }}</p>
                            <div class="blog-meta clearfix">
                                <p class="pull-left">
                                    <i class="icon-user"></i> by <a href="#">{{ twit.0 }}</a>
                                    <i class="icon-calendar"></i> {{  twit.1}}

                                </p>
                            </div>

                        </div>
                    {% endfor %}
                </div>
            </div>
            <aside class="span4">
                <a href="/search/user">Follow someone</a>
            </aside>
        </div>
    </section>
    <style>
        #twit-post label{
            display: none;
        }
        #twit-post input[type='text']{
            width:95%;
        }
        aside{
            border: 1px solid red;
            padding: 10px;
        }
        i{margin-right: 5px}
    </style>
{% endblock %}

templates/my_twits.html
{% extends 'base.html' %}
{% block content %}
    {% for twit in twit_list %}
        <div class="blog-item well">
            <p>{{ twit.content }}</p>
            <div class="blog-meta clearfix">
                <p class="pull-left">
                    <i class="icon-user"></i> by <a href="#">{{ twit.author }}</a>
                    <i class="icon-calendar"></i> {{  twit.updated_on }}
                    <i class="icon-pencil"></i><a href="{% url 'edit_twit' twit.pk %}">Edit</a>
                </p>
            </div>
        </div>
    {% endfor %}
{% endblock %}